name: test/requirements-smoke

on:
  push:
    branches: [ script ]
  pull_request:
    branches: [ main ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Prepare system build deps (for scipy/numpy)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gfortran libopenblas-dev liblapack-dev libatlas-base-dev libffi-dev

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install requirements (verbose, prefer wheels)
        run: |
          pip --version
          pip install -v --no-cache-dir --prefer-binary -r requirements.txt -r requirements-datascience.txt pytest

      - name: Run import smoke test
        run: python -m pytest -q tests/test_imports.py